# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Superior Shavings - Premium Kiln-Dried Pine Woodshavings for Poultry, Horses & Small Animals"
email: jarrod@breederschoice.com.au
description: >- # this means to ignore newlines until "baseurl:"
  Premium kiln-dried pine woodshavings for horse bedding, poultry litter, and small animal bedding. 
  High-absorbency, dust-extracted, all-natural animal bedding manufactured in Australia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://superiorshavings.github.io" # the base hostname & protocol for your site
logo: "/images/logo.svg"

# SEO specific settings
author: Superior Shavings
twitter:
  username: SuperiorShavings
  card: summary_large_image
facebook:
  publisher: superiorshavings
social:
  name: Superior Shavings
  links:
    - https://twitter.com/SuperiorShavings
    - https://facebook.com/superiorshavings

# Keywords for SEO
keywords:
  pine shavings, horse bedding, poultry bedding, animal bedding, kiln dried shavings,
  dust extracted shavings, pine woodshavings, equine bedding, chicken litter,
  small animal bedding, livestock bedding, absorbent bedding, stable bedding,
  bulk animal bedding, premium wood shavings

lang: en_AU
locale: en_AU

stockistscsv: https://dl.dropbox.com/s/c4rl2z56dkohbzg/superior_shavings.csv

# Build settings
markdown: kramdown

repository: superiorshavings/superiorshavings.github.io

plugins:
  - jekyll-email-protect
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
